### ISSUE TITLE
Opportunistic mutations

### ISSUE THREAD

**Issue by llogiq** [llogiq/mutagen#51]
I've previously [written up](https://llogiq.github.io/2018/03/03/opportune.html) a plan how to implement certain mutations, now here is the tracking issue for them.

* [x] ops traits (done with #49)
* [ ] #12 swap binary ops (+ → -, etc.)
* [ ] #21 insert clones for cloneable &mut values
* [ ] short-circuit unary ops (-x → x, !x → x)
* [ ] report effective mutations
